# Generated by Django 4.2 on 2024-04-11 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='e1_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='e1/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='e2_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='e2/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='original_image',
            field=models.FileField(default=1, upload_to='input/'),
            preserve_default=False,
        ),
    ]
