# Generated by Django 4.2 on 2024-04-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_images_image_images_e1_image_images_e2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='e0_image',
            field=models.FileField(default=1, upload_to='e0/'),
            preserve_default=False,
        ),
    ]
